[project]
name = "gestionnaire-de-mots-passe"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.14.1",
    "pytest>=8.4.1",
    "ruff>=0.11.10",
    "ttkbootstrap>=1.13.10",
]
